[#GEA] Implementing grid based map
PSW-2020-ORG6/Healthcare-System pull request #10
Opened 2020-11-13 19:25 UTC by lemara98

I have changed the entire map template to allow the changes on the map to only specific places on the map.

2020-11-13 20:53 UTC, lukaDoric requested changes

2020-11-13 20:53 UTC, lukaDoric commented on GraphicEditor/MainWindow.xaml.cs
> +            //Application.Current.MainWindow.MinWidth = 800;
Delete unnecessary code 🗡️

2020-11-13 21:03 UTC, Ana00000 approved these changes

2020-11-13 22:13 UTC, milicasiriski reviewed
There's not much code, mostly xaml 😄 so let's just wait for your teammates to check if everything is according to guidelines

2020-11-13 22:13 UTC, milicasiriski commented on GraphicEditor/MainWindow.xaml.cs
> +
extra empty lines

2020-11-13 22:59 UTC, lukaDoric approved these changes

2020-11-13 23:03 UTC, VladimirBudjen approved these changes

2020-11-14 00:16 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Implementing grid based map [1]](https://trello.com/c/KhQxETHK/42-1-implementing-grid-based-map-1)

2020-11-14 10:48 UTC, merged