[#GEA] Building And Room Information Edit - finished
PSW-2020-ORG6/Healthcare-System pull request #24
Opened 2020-11-24 22:16 UTC by lemara98

Feature left from Sprint 1- It will be updated after Database completion

2020-11-24 23:13 UTC, Ana00000 reviewed
Nice job. :)

2020-11-24 23:13 UTC, Ana00000 commented on GraphicEditor/ViewModel/RoomUpdateViewModel.cs
> +            }
Is this the best name for this method?

2020-11-24 23:14 UTC, Ana00000 approved these changes

2020-11-25 11:02 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomUpdateViewModel.cs
> +            }
If it's a dialog feature, appropriate names could be onRoomInfoConfirm and onRoomInfoCancel and it could be handled from the parent element I could help you implement the pattern that I normally use with dialogs

2020-11-25 11:03 UTC, milicasiriski requested changes
Looks good, room info update dialog could be improved. It doesn't really make sense to do reverse the changes if the update is cancelled

2020-11-27 12:26 UTC, milicasiriski requested changes
Something weird is going on on this branch 😭  I can't find the interface you've added, I've tried pulling everything but that file is missing. You need to resolve conflicts anyway so I think it will be fine after, just check if you've pushed all changes from your local branch

2020-11-27 12:26 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +            //OnPropertyChanged("BedInfo");
You don't need these anymore 😄

2020-11-27 12:26 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +
exxtra white space

2020-11-27 12:26 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +        }
You don't need this either

2020-11-27 17:31 UTC, milicasiriski approved these changes

2020-11-28 23:13 UTC, lukaDoric approved these changes

2020-11-28 23:26 UTC, merged