Gea feature/add building
PSW-2020-ORG6/Healthcare-System pull request #30
Opened 2020-11-28 17:20 UTC by hadzija7

Please approve

2020-11-29 11:31 UTC, milicasiriski requested changes

2020-11-29 11:31 UTC, milicasiriski commented on GraphicEditor/HelpClasses/Constants.cs
> +        public const string EMPTYFIELD = "emptyField";
EMTPY_FIELD

2020-11-29 11:31 UTC, milicasiriski commented on GraphicEditor/Resources/buildingStyles.txt
> +﻿
Was this file left accidentally?

2020-11-29 11:31 UTC, milicasiriski commented on GraphicEditor/View/Windows/AddBuilding.xaml.cs
> +            AddBuildingViewModel.GetInstance().Window = this;
Avoid singletons

2020-11-29 11:31 UTC, milicasiriski commented on GraphicEditor/ViewModel/DBtest.cs
> +            }
😄

2020-11-29 11:31 UTC, milicasiriski commented on GraphicEditor/ViewModel/HospitalMapUserControlViewModel.cs
> +            System.Console.WriteLine(but.Content);
probably left here by mistake

2020-11-30 15:57 UTC, milicasiriski approved these changes

2020-11-30 17:59 UTC, lukaDoric approved these changes

2020-11-30 18:00 UTC, VladimirBudjen approved these changes

2020-11-30 18:00 UTC, markovidovic approved these changes

2020-11-30 18:16 UTC, merged