display scheduled appointments,frontend and backend
PSW-2020-ORG6/Healthcare-System pull request #47
Opened 2020-12-05 13:43 UTC by maka998

2020-12-05 13:53 UTC, maka998 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)WA-3.6 As a patient I want to be able to see all scheduled appointments in order to get the information I need.](https://trello.com/c/Wws6gYK4/25-3wa-36-as-a-patient-i-want-to-be-able-to-see-all-scheduled-appointments-in-order-to-get-the-information-i-need)

2020-12-05 15:31 UTC, milicasiriski requested changes
Good PR! Try not to comment old code because most of it is used somewhere and could lead to bugs, if something is causing problems tell me so we can solve it without affecting the rest of the app.

2020-12-05 15:31 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/IRegistrationRepository.cs
> +        public List<FamilyDoctorDTO> GetAllGeneralPractitionerPhysitions();
typo

2020-12-05 15:31 UTC, milicasiriski commented on WebApplication/Backend/Services/RegistrationService.cs
> +            return registrationRepository.GetAllGeneralPractitionerPhysitions();
typo

2020-12-05 15:31 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/ProcedureTypeRepository.cs
> +        /*
if it's not used or not working delete it

2020-12-05 15:31 UTC, milicasiriski commented on WebApplicationTests/AppointmentTests.cs
> +            WebApplication.Backend.Services.AppointmentsService service = new WebApplication.Backend.Services.AppointmentsService(stubRepository.Object);
import this service so you don't need to reference it like this

2020-12-05 15:31 UTC, milicasiriski commented on WebApplicationTests/AppointmentTests.cs
> +            stubRepository.Setup(m => m.GetAllAppointmentByPatientId(patientIdTrue)).Returns(appointments);
💯

2020-12-05 15:31 UTC, milicasiriski commented on project-generated-code-backend/Backend/Controller/PhysitianControllers/PhysitianHospitalAccountsController.cs
> +        /*
throw Not Implemented Exception if it requires parameter

2020-12-05 15:31 UTC, milicasiriski commented on project-generated-code-backend/Backend/Controller/PhysitianControllers/PhysitianScheduleController.cs
> +        /*
throw not implemented exception

2020-12-05 15:31 UTC, milicasiriski commented on project-generated-code-backend/Backend/Model/Schedule/Appointment.cs
> +        /*
Why is this commented?

2020-12-05 15:31 UTC, milicasiriski commented on project-generated-code-backend/Backend/Service/SchedulingService/PhysitianScheduleService.cs
> +        }/*
why is this commented?

2020-12-05 15:31 UTC, milicasiriski commented on project-generated-code-backend/Backend/Service/SchedulingService/PhysitianScheduleService.cs
> +        }*/
same

2020-12-06 10:45 UTC, milicasiriski approved these changes

2020-12-06 16:03 UTC, VladimirBudjen requested changes
PhysiTian X
PhysiCian ✓

2020-12-06 16:03 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/RegistrationController.cs
> +            return registrationService.GetAllPhysitians();
physiCians was good :(

2020-12-06 16:03 UTC, VladimirBudjen commented on WebApplication/Backend/Repositorys/IRegistrationRepository.cs
> +        public List<FamilyDoctorDTO> GetAllGeneralPracticePhysitians();
*GetAllGeneralPracticePhysicians

2020-12-06 16:16 UTC, VladimirBudjen approved these changes

2020-12-06 16:44 UTC, merged