[#IA]Grpc protocol
PSW-2020-ORG6/Healthcare-System pull request #50
Opened 2020-12-09 14:15 UTC by milica-okiljevic

2020-12-09 18:14 UTC, milicasiriski requested changes
Good PR! Delete the .idea folder please 😄

2020-12-09 18:14 UTC, milicasiriski commented on IntegrationAdaptersTests/ActionsAndBenefitsTests.cs
> +        }
No assert method in this test

2020-12-09 18:14 UTC, milicasiriski commented on IntegrationAdaptersTests/ActionsAndBenefitsTests.cs
> +        public Guid guid2 = new Guid("a69b4d8e-55ce-4cdf-bfa6-7462e085a909");
This is a good practice, to separate test objects that you use into fields, you should extend this and make ActionAndBenefitsMessage test object here and then use it in the tests - they will contain less code and be more readable

2020-12-09 18:14 UTC, milicasiriski commented on IntegrationAdaptersTests/ActionsAndBenefitsTests.cs
> +            mock.Setup(expression: t => t.GetActionAndBenefitMessegeByID(It.IsAny<Guid>())).Returns( new ActionAndBenefitMessage { ActionID = guid, PharmacyName = "Jankovic", Text = "50% off brufen",
To continue on the previous comment, just instantiate this ActionAndBenefitsMessage in the field and use it in all the tests

2020-12-09 18:14 UTC, milicasiriski commented on IntegrationAdaptersTests/ActionsAndBenefitsTests.cs
> +            ,new ActionAndBenefitMessage { ActionID = new Guid("0e90a9a7-2722-45bb-a3de-7832131dcfe3"), PharmacyName = "BENU",Text = "2 vitamins Mg for 1 price", DateFrom= new DateTime(2020, 2, 16),
And extract the other ActionsAndBenefitsMessage as well and you can just make the list here

2020-12-09 18:14 UTC, milicasiriski commented on IntegrationAdaptersTests/ActionsAndBenefitsTests.cs
> +            ,new ActionAndBenefitMessage { ActionID = new Guid("0e90a9a7-2722-45bb-a3de-7832131dcfe3"), PharmacyName = "BENU",Text = "2 vitamins Mg for 1 price", DateFrom= new DateTime(2020, 2, 16),
For example new List<ActionsAndBenefitsMessage> { actionsAndBenefits1, actionsAndBenefits1}

2020-12-10 10:10 UTC, dragana-todorovic approved these changes

2020-12-10 11:48 UTC, milicasiriski approved these changes

2020-12-10 11:48 UTC, merged