[#IA] Send and receive message from pharmacy completed
PSW-2020-ORG6/Healthcare-System pull request #55
Opened 2020-12-10 21:19 UTC by milica-okiljevic

2020-12-11 12:48 UTC, milicasiriski requested changes
Good PR! Try to simplify public methods and put anything that creates strings into private methods.

2020-12-11 12:48 UTC, milicasiriski commented on IntegrationAdapters/gRPCProtocol/ClientScheduleService.cs
> +                Console.WriteLine(response.Response + " is response;status: " + response.Status);
delete all console writes 😄

2020-12-11 12:48 UTC, milicasiriski commented on IntegrationAdapters/gRPCProtocol/NetGrpcServiceImpl.cs
> +            this.MessageResponseFromPharmacy = request.MedicineName;
What do you need these fields for?

2020-12-11 12:48 UTC, milicasiriski commented on IntegrationAdapters/gRPCProtocol/NetGrpcServiceImpl.cs
>              response.Status = "STATUS OK";
I've noticed this just now, this could go into a private method like generate response

2020-12-11 12:48 UTC, milicasiriski commented on IntegrationAdapters/gRPCProtocol/ClientScheduleService.cs
> +        public void setingResponse(String message)
SetResponse?

2020-12-11 12:48 UTC, milicasiriski commented on IntegrationAdapters/Models/MedicineMessage.cs
> +        public MedicineMessage(string MedicineName, int Quantity, bool IsPharmacyApproved)
function parameters start with lowercase, medicineName, quantity, isPharmacyApproved

2020-12-11 20:59 UTC, milicasiriski requested changes

2020-12-11 20:59 UTC, milicasiriski commented on IntegrationAdapters/Program.cs
> +        public static String ResponseMessageGrpc;
use string (basic type) instead of String (class) - same difference as int and Integer in Java

2020-12-11 20:59 UTC, milicasiriski commented on IntegrationAdapters/gRPCProtocol/ClientScheduleService.cs
> +        public String MessageResponseFromPharmacy { get; set; }
string

2020-12-12 14:57 UTC, milicasiriski approved these changes

2020-12-12 14:58 UTC, lukaDoric approved these changes

2020-12-12 18:47 UTC, merged