Gea feature/appoitment hadzi
PSW-2020-ORG6/Healthcare-System pull request #65
Opened 2020-12-14 22:05 UTC by stefanwert

Gea team sprint 3

2020-12-14 22:06 UTC, Ana00000 approved these changes

2020-12-14 22:08 UTC, lemara98 approved these changes
NOT GREAT, NOT TERRIBLE

2020-12-14 22:46 UTC, milicasiriski requested changes

2020-12-14 22:46 UTC, milicasiriski commented on GraphicEditor/MainWindow.xaml
> +    <!--<Window.Resources>
Delete if unnecessary

2020-12-14 23:10 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Overview of equipment and medicine](https://trello.com/c/rPYPh29q/48-3-overview-of-equipment-and-medicine)

2020-12-14 23:11 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Advanced search for objects on the map](https://trello.com/c/WXu6JZ3f/47-3-advanced-search-for-objects-on-the-map)

2020-12-14 23:11 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Advanced search for equipment and medicine](https://trello.com/c/dMXlbrcR/50-3-advanced-search-for-equipment-and-medicine)

2020-12-14 23:45 UTC, Ana00000 approved these changes

2020-12-21 18:03 UTC, milicasiriski requested changes
I'm glad you set up the shared database, but please use services to access it. If there aren't any existing services or you're not sure how to find them just make your own and use them.
Change the PR title to something more meaningful please, at least the user stories you covered with it.

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/UserControls/CardiologyBuildingUserControl.xaml
> +    <!--<UserControl.Resources>
delete if unused

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/UserControls/CardiologySecondFloorMapUserControl.xaml.cs
> +    //public partial class CardiologySecondFloorMapUserControl : UserControl
delete if unnecessary

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/Appointment.xaml.cs
> +            //setuj ovde !!!
hahaha

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/Appointment.xaml.cs
> +            //setuj ovde !!!
Okay this class has a lot of comments that may be confusing later so just clean up, if there is something missing you can add // TODO: with something sensible that is missing

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/Appointment.xaml.cs
> +                // Call OnPropertyChanged whenever the property is updated
if this was not generated, it can be deleted

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/AppointmentList.xaml.cs
> +
one empty line is enough

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/EquipmentDetails.xaml.cs
> +            Equipments = equipmentDatabaseSql.GetAll().Where(r => r.RoomId.Equals(_roomIdSerialNumber)).ToList();
I think you will get the equipment with the room from repository, either way this is something that should be done through backend, view model needs to access the repository through at least the service layer

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/View/Windows/EquipmentDetails.xaml.cs
> +            Equipments = equipmentDatabaseSql.GetAll().Where(r => r.RoomId.Equals(_roomIdSerialNumber)).ToList();
View layer should definitely not reference the repository let alone call database directly

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/CardiologyFirstFloorMapUserControlViewModel.cs
> +        PatientDatabaseSql patientRepository = new PatientDatabaseSql();
This is a little better than calling repository from view, but still it could be all located in one service and then the viewmodel could just call the service methods

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/CardiologyFirstFloorMapUserControlViewModel.cs
> +        PatientDatabaseSql patientRepository = new PatientDatabaseSql();
Ideally the service would work on another thread

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/EquipmentSearchViewModel.cs
> +        }
This is basically business logic that a service should handle and return the result to the viewmodel

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/HospitalMapUserControlViewModel.cs
> +        //_viewModel.HospitalMap.hospitalMapGrid
comments

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/HospitalMapUserControlViewModel.cs
> +            foreach (Building building in buildingRepository.GetAll())
I know this is too simple and doesn't handle any business logic but it should still go into service

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/MedicineSearchViewModel.cs
> +        private MedicineDatabaseSql medicineRepository = new MedicineDatabaseSql();
Same here, a lot of repositories to complete a search query that should be handled in a service

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +        //private Object selectedItem;
comments

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +        //public string RoomName
comments

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +            bedVisibility = Visibility.Hidden;
You can bind visibility just like any other property, please don't reference the view from view model

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +            //OnPropertyChanged("Beds");
comments

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomInformationViewModel.cs
> +            bedVisibility = Visibility.Hidden;
You already have properties and everything?

2020-12-21 18:03 UTC, milicasiriski commented on GraphicEditor/ViewModel/RoomSearchViewModel.cs
> +        private BuildingDatabaseSql buildingRepository = new BuildingDatabaseSql();
Again with the search - use service to generate results

2020-12-25 13:48 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Controllers, services and repositories for GEA](https://trello.com/c/LjY3MhGI/88-3-controllers-services-and-repositories-for-gea)

2020-12-25 13:48 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Controllers, services and repositories for GEA](https://trello.com/c/LjY3MhGI/88-3-controllers-services-and-repositories-for-gea)

2020-12-25 13:48 UTC, Ana00000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Dynamic switch of screens](https://trello.com/c/kIZnTtdS/89-3-dynamic-switch-of-screens)

2020-12-29 08:00 UTC, closed without merging