[#WA-1.1 - WA-1.5]Feature/functionalities
PSW-2020-ORG6/Healthcare-System pull request #7
Opened 2020-11-08 16:59 UTC by Aleksandra988

2020-11-08 17:57 UTC, VladimirBudjen requested changes

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Controllers/PatientController.cs
> +        ///</returns>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        ///</exception>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        ///</param>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        ///</param>
Remove these comments, if they are unnecessary.

2020-11-08 17:57 UTC, VladimirBudjen commented on WebApplication/Backend/Repositorys/PatientRepository.cs
> +        ///</exception>
Remove these comments, if they are unnecessary.

2020-11-08 18:01 UTC, lukaDoric requested changes

2020-11-08 18:01 UTC, lukaDoric commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string sql1 = "Select * from feedbacks";
Can you rename this string to something more appropriate?

2020-11-08 18:01 UTC, lukaDoric commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string sql1 = "Select * from feedbacks";
Also cmd1, rdr.

2020-11-08 18:10 UTC, markovidovic commented on WebApplication/wwwroot/app/admin.js
> +    		    <a class="nav-link" data-toggle="tab" href="#disaproved">Disaproved</a>
You misspelled disapproved.

2020-11-08 18:13 UTC, VladimirBudjen commented on WebApplication/Backend/Util/MyDbContext.cs
> +                    //new Feedback { PatientId = "0003", Text = "komentara3", Date = new DateTime(2017, 1, 18), Approved = true }
if you dont use these lines, delete them

2020-11-08 18:19 UTC, markovidovic commented on WebApplication/Migrations/20201106203752_mm1.cs
> +    public partial class mm1 : Migration
If you could change class name of mm1 to something more understandable.

2020-11-08 19:41 UTC, VladimirBudjen approved these changes

2020-11-08 20:50 UTC, milicasiriski requested changes
The repositories need some refactoring and migration name should be more readable. A really good PR, but could be better 😄 Also we all need to discuss code formatting and where to use white spaces

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        ///</returns>
This is documentation I believe, so it's ok

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Controllers/FeedbackController.cs
> +        [HttpGet("noapproved")]
You should think of some rules for these paths so that they are uniform and same everywhere, for example you could use Camel notation, or underscore or whatever, it's fine with me as long as you all stick to the same standard.

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string sql1 = "Select * from feedbacks";
Yes, and they should also be constants - to prevent other coders from changing them and then causing some unexpected behavior.

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +
Delete this empty row

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        internal List<Feedback> GetFeedbacks(Boolean approvedF)
Is approvedF a typo or is it short for something?

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        internal List<Feedback> GetFeedbacks(Boolean approvedF)
You could also refactor the entire class:
Extract the code that connects to the data base to one function that accepts sql select command as a parameter. That way you could just call that method from each of the getters (getAll, getApproved, getDisapproved) with an appropriate sql query 😄

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string[] partsOfDate = dateString[0].Split("/");
I don't think you need to parse date this way, there are getters for day, month, year, hour, minute...

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string[] partsOfDate = dateString[0].Split("/");
Actually I think there's a method in DateTime class that returns string in any format you need.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
It's really well supported unlike Date in Java 😄

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +                string sqlQueryAdd = "INSERT INTO feedbacks (text,approved,date,patientid,serialnumber)  VALUES('" + feedback.Text + "','" + 0 + "','" + partsOfDate[2] + "-" + partsOfDate[1] + "-" +
This name is a lot better, but this is actually not a query but dml 😄 Let's change that just in case

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/PatientRepository.cs
> +
Extra empty rows

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/PatientRepository.cs
> +                return resultList;
Same as with FeedbackRepository, you should extract the db connection to one method and then have other methods call that. Although for now there is only one such method, it's creating more layers of abstraction which is also a good and clean practice.

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Services/FeedbackService.cs
Extra empty row

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Services/FeedbackService.cs
> +        }
This method should be called ApproveFeedback as that is the only field being changed

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Backend/Services/PatientService.cs
> +
Extra empty row

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Migrations/20201106124846_migr1.Designer.cs
> +                            Contact = "kontaktMica",
ahahhaahhahaha

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Migrations/20201106124846_migr1.cs
> +    public partial class migr1 : Migration
If you are naming these classes, please give them some sensible names like Migration1 😄

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/Migrations/20201106202412_mm.cs
> +    public partial class mm : Migration
Class name

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +			noapprovedFeedbacks: null,
disapproved?

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +											<td v-for="p in patients" v-if="parseInt(p.id) == parseInt(f.patientId)">{{p.name}} {{p.surname}}</td>
Does equals not work?

2020-11-08 20:50 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +						alert("Textarea is empty.");
Typo, also this should warn user so you should put something more helpful and polite

2020-11-08 20:50 UTC, milicasiriski commented on project-generated-code-backend/Backend/Dto/FeedbackDTO.cs
> +            return words != null && Text != null && Text.Length > 2;
Maybe do a null check on Text before calling split method 😄

2020-11-08 20:50 UTC, milicasiriski commented on project-generated-code-backend/Backend/Dto/FeedbackDTO.cs
> +        public bool CorrectText()
Methods that return bool values usually start with is, or has, for example isTextCorrect

2020-11-08 20:50 UTC, milicasiriski commented on project-generated-code-backend/Backend/Dto/FeedbackDTO.cs
> +        }
This method is really confusing the name suggests that you are checking if Approve is false, so maybe change to IsApprovalValid

2020-11-08 20:50 UTC, milicasiriski commented on project-generated-code-backend/Backend/Dto/FeedbackDTO.cs
> +namespace health_clinic_class_diagram.Backend.Dto
Also methods should go under fields and getters/setters

2020-11-08 20:50 UTC, milicasiriski commented on project-generated-code-backend/Backend/Model/Blog/Feedback.cs
> +        public Feedback(FeedbackDTO feedbackDTO)
👍

2020-11-09 19:46 UTC, milicasiriski requested changes
Service class shouldn't set query strings that is repository's responsibility. Also there are some typos on frontend 😄 Btw I like that you've deleted the migration classes

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +						alert("Tou need to enter a comment first.");
Tou have made a typo 😄

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +				alert("Tou need to enter a comment first.");
same

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/PatientRepository.cs
> +        internal List<Patient> GetPatients(String sqlDml)
You shouldn't set the sql query through parameter, this is repository's job, not service's

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/Backend/Services/FeedbackService.cs
> +            return feedbackRepository.GetFeedbacks("Select * from feedbacks");
This query needs to be in the repository

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/Backend/Services/FeedbackService.cs
> +            return feedbackRepository.GetFeedbacks("Select * from feedbacks where approved is true");
query in repo

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/Backend/Services/FeedbackService.cs
> +            return feedbackRepository.GetFeedbacks("Select * from feedbacks where approved is false");
same

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +        internal List<Feedback> GetFeedbacks(String sqlDml)
Just make this a private method, and make three public methods: GetAllFeedbacks, GetApprovedFeedbacks, GetDisapprovedFeedbacks and set the sql query string in those methods, then call this one from each of them.

2020-11-09 19:46 UTC, milicasiriski commented on WebApplication/wwwroot/app/patient.js
> +						alert("Tou need to enter a comment first.");
Or did you mean to write thou?

2020-11-09 20:24 UTC, milicasiriski approved these changes

2020-11-09 20:24 UTC, milicasiriski commented on WebApplication/Backend/Repositorys/FeedbackRepository.cs
> +            return GetFeedbacks("Select * from feedbacks where approved is false");
💯

2020-11-09 20:28 UTC, VladimirBudjen approved these changes

2020-11-09 20:30 UTC, lukaDoric approved these changes

2020-11-09 21:19 UTC, merged