Finished login
PSW-2020-ORG6/Healthcare-System pull request #83
Opened 2021-01-07 21:34 UTC by repovic48

2021-01-07 22:38 UTC, milicasiriski requested changes
Fix the Start-up and build errors first to make sure everything is ok, then we'll look at the rest.

2021-01-07 22:38 UTC, milicasiriski commented on WebApplication/Startup.cs
> +                    CreateConnectionStringFromEnvironment(),
use connectionString variable (this was changed when you resolved conflicts)

2021-01-07 22:38 UTC, milicasiriski commented on WebApplication/Startup.cs
> +            services.AddScoped<Backend.Repositorys.Interfaces.IAdminRepository, AdminDatabaseSql>();
Just import IAdminRepository from backend, you probably already have so just delete the namespace path part

2021-01-07 22:38 UTC, milicasiriski commented on WebApplication/Startup.cs
> +            string password = Environment.GetEnvironmentVariable("DATABASE_PASSWORD") ?? "root";
Delete this, also a mistake from conflict resolution and this is causing your build errors

2021-01-08 17:55 UTC, milicasiriski approved these changes
Good PR, a couple of comments are left here and there.

2021-01-08 17:55 UTC, milicasiriski commented on project-generated-code-backend/Backend/Model/Accounts/Admin.cs
> +        [JsonConstructor]
Delete json constructor annotation, there can be only one

2021-01-08 17:55 UTC, milicasiriski commented on project-generated-code-backend/Backend/Model/Accounts/Physician.cs
> +        /*
You can delete this if no one is using it

2021-01-08 17:55 UTC, milicasiriski commented on project-generated-code-backend/Backend/Repository/Generic/IAdminRepository.cs
> +        //5555555555555555555555555555555555555555
hahah what is this?

2021-01-08 18:55 UTC, milicasiriski approved these changes

2021-01-08 20:53 UTC, Tanjaa1 approved these changes

2021-01-08 21:13 UTC, merged