Wa -microservices
PSW-2020-ORG6/Healthcare-System pull request #92
Opened 2021-01-11 14:58 UTC by Aleksandra988

2021-01-16 14:02 UTC, milicasiriski requested changes
As far as I can see it's mostly moving the files from your project into different microservices but we just need to check about the separate database contexts because of the docker deployment

2021-01-16 14:02 UTC, milicasiriski commented on MicroServiceAccount/Backend/Model/Admin.cs
> +        }
Delete one of the JsonConstructor annotations, there can be only one or the app could break

2021-01-16 14:02 UTC, milicasiriski commented on MicroServiceAccount/Backend/Model/Patient.cs
> +        //}
Delete this if unused

2021-01-16 14:02 UTC, milicasiriski commented on MicroServiceAccount/Backend/Repository/DatabaseSql/MsAccountDbContext.cs
> +        //          "User ID =postgres;Password=super;Server=localhost;Port=5432;Database=healthcare-system-db;Integrated Security=true;Pooling=true;";
You can delete this, it's not and should not be used

2021-01-16 14:02 UTC, milicasiriski commented on MicroServiceAccount/Backend/Repository/DatabaseSql/MsAccountDbContext.cs
> +        //          "User ID =postgres;Password=super;Server=localhost;Port=5432;Database=healthcare-system-db;Integrated Security=true;Pooling=true;";
Okay now I see that the whole DbContext is moved and refactored here, I think the data should still be kept in the same database but extracted from different microservices (from their repositories?) but we can check with someone about that

2021-01-16 14:02 UTC, milicasiriski commented on MicroServiceAppointment/Backend/Model/Appointment.cs
> +        }
Delete this if unused

2021-01-16 14:02 UTC, milicasiriski commented on WebApplication/Controller/Enumerable.cs
> +    }
Was this class created by accident?

2021-01-16 23:37 UTC, Tanjaa1 commented on WebApplication/Controller/Enumerable.cs
> +    }
Yes :(

2021-01-18 19:42 UTC, milicasiriski reviewed
Looks ok now, I will change the docker files and it's good to go, and please try to make commit messages make more sense...

2021-01-20 13:07 UTC, milicasiriski approved these changes

2021-01-20 13:09 UTC, lukaDoric approved these changes

2021-01-20 13:19 UTC, merged